---
- hosts: lxc
  sudo: yes
  tasks:
    - action: apt pkg=software-properties-common state=present
    - action: apt_repository repo=ppa:rethinkdb/ppa
    - action: apt_repository repo=ppa:dotcloud/lxc-docker
    - action: apt_repository repo=ppa:chris-lea/node.js
    - action: apt update_cache=yes

    - action: apt pkg=rethinkdb state=present
    - command: cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf creates=/etc/rethinkdb/instances.d/default.conf
    - action: apt pkg=lxc-docker state=present
    - action: apt pkg=nodejs state=present
    - action: apt pkg=libzmq-dev state=present
    - action: get_url url=http://aphyr.com/riemann/riemann_0.2.2_all.deb dest=/tmp/
    - action: command dpkg -i /tmp/riemann_0.2.2_all.deb creates=/usr/bin/riemann
